[supervisord]
nodaemon=true

[program:php-fpm]
command=php-fpm
autostart=true
autorestart=true

[program:nginx]
command=nginx -g "daemon off;"
autostart=true
autorestart=true

[program:migrate]
command=bash -c "php artisan migrate --force && php artisan config:cache && php artisan route:cache"
autostart=true
autorestart=false
startsecs=0
